### ISSUE TITLE
Mesa Subgraph Entity Model

### ISSUE THREAD

**Issue by nicoelzer** [cryptonative-ch/mesa-subgraph#1]
Current Entities to be finalized:

**Auction** {
      id: string // Contract address (Using Factory pattern)
      startBlock: number // Open block
      endBlock: number // Close auction
      tokenIcon: string // Token icon, preferably are URL on the IPFS
      tokenAddress: string // ERC20 Token's contract address
      tokenSymbol: string // Symbol
      tokenAmount: number // Amount auctioned to buyers/bidders
      tokenName: string // Name
      bids: AuctionBid[]
}

**AuctionBid** {
      sellAmount: BigNumber // Number of tokens the investor wants to buy
      buyAmount: BigNumber // Price at which they wish to buy
      address: string // Their Ethereum address
}

**Comment by aabot123** [comment]
This looks good.  **Couple notes**:

Auction
- the keys are token specific, as is the schema it seems - if so and only using this entity for this specific purpose, we want to get  more descriptive  ex. TokenAuction
- this means we don't need to be redundant with the keys.  ie icon instead of tokenIcon etc.
-  some of these are behind a paywall.  tokenIcon is at least on Etherscan
- separated amountAvailable and amountAuctioned - please comment if not relevant.

AuctionBid
-  would suggest TokenAuctionBid
-  would it be more accurate to label the other two. ie. amount and price
-  biddingAddress

**Suggested Revision:**

TokenAuction {
id: string // Contract address (Using Factory pattern)
startBlock: number // Open block
endBlock: number // Close auction
icon: string // Token icon, preferably are URL on the IPFS
address: string // ERC20 Token's contract address
symbol: string // Symbol
amountAvailable: number // Amount available for auction to buyers/bidders
amountAuctioned: number // Amount auctioned
name: string // Name
bids: AuctionBid[]
}

TokenAuctionBid {
amount: BigNumber // Number of tokens the investor wants to buy
price: BigNumber // Price at which they wish to buy
walletAddress: string // Their Ethereum address
}

**Comment by nicoelzer** [comment]
@aabot123 looks great!

Some thoughts about additional information we could already add:

**TokenAuction:**
- priceNumerator / priceDenominator (While the auction is open this would be calculated with every bid, once the auction is cleared it could become the final price)
- minBuyAmount
- minimumBiddingAmountPerOrder
- minFundingThreshold
- status: open, cleared (Aggregated from  events)

**TokenAuctionBid:**
- status: open, settled, canceled, claimed (Aggregated from the different events)
